### ISSUE TITLE
Adding a ninja catalyst seller to major cities

### ISSUE THREAD

**Issue by Fridgeee** [johnnyrags/rathena#25]
Ninja Catalysts (Flame/Ice/Wind/Earth/Shadow Stones/Charms as well as the Kunais) are only purchasable from Amatsu, which is 10k a trip. It is the only job who has this issue with NPCs selling their catalysts so simply copying the NPC in Amatsu to Prontera would improve new Ninja quality of life drasticly.

For reference, the Ninja Shop NPCs can be found in the pre-re NPC files. For Prontera, I can suggest to put them inside the tool shop (prt_in) : 113, 80 and 116, 80 so it puts them on the right side of the shop but not in the way of anything else.

**Comment by johnnyrags** [comment]
NPC is already in Prontera, albeit a little hidden from normal view. May consider moving him to a more visible location.
