### ISSUE TITLE
Dewata and Naga

### ISSUE THREAD

**Issue by RhetoricalAnswer** [johnnyrags/rathena#27]
#1: Dewata NPC in Alberta is not there. All others are present as far as I can see. Will test later to see if they all work

#2: Naga in Ash Vacuum. Doing the Eden quests (111-120 range), there is one to kill Naga. There are Naga in both spl_fild01 and spl_fild02 (possibly 03 as well, irowiki says they are). However they are different levels which I've never seen, and the lower level ones in spl_fild02 don't count towards the Eden kill quest.

**Comment by johnnyrags** [comment]
NPC is in alberta, 212,202 northern docks with the two ships.

Naga situation could possibly be improperly assigned mob id for the spawn on that map, but they could also be summons. For the purpose of the quest, the correct Naga are on spl_fild01 and spl_fild03
